version: "0.2"
language: en
ignorePaths:
  - node_modules
  - .next
  - yarn.lock
  - "*.lock"
words:
  - cancellation
  - chaika
  - checkIn
  - checkOut
  - childAges
  - cspell
  - hookform
  - Jost
  - maxOccupancy
  - nextjs
  - nuqs
  - ratePlan
  - ratePlanId
  - refundable
  - roomId
  - tailwindcss
  - trivago
  - zod
